# Server Configuration
server.port=8081
server.servlet.context-path=/api

# Database Connection (H2 In-Memory - runs out-of-the-box)
# spring.datasource.url=jdbc:h2:mem:candidate_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver
# spring.h2.console.enabled=true

# JPA / Hibernate Configurations( uncomment to use)
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Database Connection 
spring.datasource.url=jdbc:postgresql://localhost:5432/candidate_db
spring.datasource.username=postgres
spring.datasource.password=Saroj1001%
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# File Upload Configurations (Up to 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger UI and OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# Configurable Engines Parameters
# Source priorities (higher number = higher priority)
app.conflict.priority.csv=1
app.conflict.priority.pdf=2

# Matching threshold and weights for candidate matching deduplication (must sum to 1.0)
app.matching.threshold=0.8
app.matching.weight.email=0.4
app.matching.weight.phone=0.2
app.matching.weight.links=0.2
app.matching.weight.name=0.2
